startCommand: gunicorn weather.wsgi:application

services:
  - type: web
    name: weather-django
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn weather.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: weather.settings
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "render.com"
